{{- if .Values.secretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretRef }}
  labels:
    {{- include "sentrix-evaluator.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnBvc3RncmVzQHBvc3RncmVzOjU0MzIvZHJpZnRfZGI=
{{ end }}
