from __future__ import annotations

from typing import TYPE_CHECKING

from evaluator.optimization.models import (
    OptimizationAction,
    OptimizationRecommendation,
)

if TYPE_CHECKING:
    from evaluator.counterfactual.models import CounterfactualResult


def score_actions(
    actions: list[OptimizationAction],
    counterfactuals: list[CounterfactualResult],
) -> list[OptimizationRecommendation]:
    """Score and rank actions using counterfactual impact estimates.

    For each action, finds the matching counterfactual result
    (by ``change_id``), then derives:

    - ``expected_improvement`` = ``counterfactual.delta``
    - ``confidence`` = ``counterfactual.confidence``

    Recommendations are sorted by:
    1. Higher ``expected_improvement`` first (primary)
    2. Higher ``confidence`` first (tie-breaker)

    Args:
        actions: Actions generated by :func:`generate_actions`.
        counterfactuals: Results from :func:`run_counterfactual_analysis`.

    Returns:
        A sorted list of :class:`OptimizationRecommendation`.
    """
    cf_by_change: dict[str, CounterfactualResult] = {}
    for cf in counterfactuals:
        change_ids = cf.metadata.get("change_ids", [])
        for cid in change_ids:
            cf_by_change[str(cid)] = cf

    recommendations: list[OptimizationRecommendation] = []

    for priority, action in enumerate(actions, start=1):
        cf = cf_by_change.get(action.change_id)
        if cf is not None:
            expected_improvement = cf.delta
            confidence = cf.confidence
            cf_metadata = cf.metadata
        else:
            expected_improvement = 0.0
            confidence = 0.0
            cf_metadata = {}

        rec = OptimizationRecommendation(
            action=action,
            expected_improvement=round(expected_improvement, 6),
            confidence=round(confidence, 4),
            priority=priority,
            metadata={
                "source": "counterfactual_simulation",
                "cf_metadata": cf_metadata,
            },
        )
        recommendations.append(rec)

    recommendations.sort(
        key=lambda r: (r.expected_improvement, r.confidence),
        reverse=True,
    )
    for i, rec in enumerate(recommendations, start=1):
        rec.priority = i

    return recommendations
